import java
active_schema='Black'
active_schema_values=\
{
'NAME'                                   :  'BLACK_BG',
'hidden'                                 :  False,
'font_name'                              : 'Dialog',
'font_bold'                              :  False,
'font_italic'                            :  False,
'font_size'                              :  14,
'background_color'                       :  java.awt.Color(0,0,0),
'booked_track_color'                     :  java.awt.Color(255,255,0),
'turnout_cricle_color'                   :  java.awt.Color(0,255,0),
'turnout_circle_thrown_color'            :  java.awt.Color(255,255,0),
'turnout_circle_size'                    :  3,
'default_track_color'                    :  java.awt.Color(255,255,224),
'default_track_color_color'              :  java.awt.Color(255,255,224),
'default_occupied_track_color'           :  java.awt.Color(255,0,0),
'default_occupied_track_color_color'     :  java.awt.Color(255,0,0),
'default_alternative_track_color'        :  java.awt.Color(255,255,255),
'default_alternativeTrack_color_color'   :  java.awt.Color(255,255,255),
'block_contents_icon'                    :  {'color' : java.awt.Color(255,175,175), 'font' : 'Dialog         ', 'size' : 14 , 'bold' : True, 'italic' : False, 'hidden' : False},
'positionable_labels'                    :  {'PS01_17'                      : {'color' : java.awt.Color(0,255,0)     , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'PS01_4'                       : {'color' : java.awt.Color(0,255,0)     , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'PS01_12'                      : {'color' : java.awt.Color(0,255,0)     , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'BL6 (BS01_32)'                : {'color' : java.awt.Color(255,255,0)   , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : False},
                                             'BL5 (BS01_33)'                : {'color' : java.awt.Color(255,255,0)   , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : False},
                                             'testRoute3'                   : {'color' : java.awt.Color(255,255,255) , 'font' : 'Times Roman    ', 'size' : 14 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'testRoute2'                   : {'color' : java.awt.Color(255,255,255) , 'font' : 'Times Roman    ', 'size' : 14 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'testRoute1'                   : {'color' : java.awt.Color(255,255,255) , 'font' : 'Times Roman    ', 'size' : 14 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'shunt8691'                    : {'color' : java.awt.Color(255,175,175) , 'font' : 'Dialog         ', 'size' : 14 , 'bold' : True , 'italic' : False, 'hidden' : False},
                                             'TO01_4'                       : {'color' : java.awt.Color(255,255,0)   , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'PS01_13'                      : {'color' : java.awt.Color(0,255,0)     , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'PS01_14'                      : {'color' : java.awt.Color(0,255,0)     , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : True},
                                             'BL3 (BS01_39)'                : {'color' : java.awt.Color(255,255,0)   , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : False},
                                             'BL2 (BS01_34)'                : {'color' : java.awt.Color(255,255,0)   , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : False},
                                             'BL1 (BS01_35)'                : {'color' : java.awt.Color(255,255,0)   , 'font' : 'Dialog         ', 'size' : 12 , 'bold' : True , 'italic' : False, 'hidden' : False},
                                             
                                        },
}